import {createConstants} from '../utils';

export default createConstants(
  'REQUEST_STARTED',
  'REQUEST_COMPLETED',
  'REQUEST_FAIL',
  'FETCH_MOVIE_GENRES_DATA_SUCCESS', 
  'FETCH_MOVIE_GENRES_DATA_FAILURE',  
  'FETCH_MOVIE_DATA_SUCCESS',
  'FETCH_MOVIE_DATA_FAILURE',
  'FETCH_GENRE_MOVIE_DATA_FAILURE',
  'FETCH_GENRE_MOVIE_DATA_SUCCESS',

);
